// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT backHomeButton

lv_obj_t * ui_backHomeButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_backHomeButton;
    cui_backHomeButton = lv_imagebutton_create(comp_parent);
    lv_imagebutton_set_src(cui_backHomeButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_242677916, NULL);
    lv_obj_set_height(cui_backHomeButton, lv_pct(6));
    lv_obj_set_width(cui_backHomeButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_backHomeButton, -206);
    lv_obj_set_y(cui_backHomeButton, -217);
    lv_obj_set_align(cui_backHomeButton, LV_ALIGN_CENTER);
    lv_obj_set_style_image_recolor(cui_backHomeButton, lv_color_hex(0xFCF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(cui_backHomeButton, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BACKHOMEBUTTON_NUM);
    children[UI_COMP_BACKHOMEBUTTON_BACKHOMEBUTTON] = cui_backHomeButton;
    lv_obj_add_event_cb(cui_backHomeButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_backHomeButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_backHomeButton_create_hook(cui_backHomeButton);
    return cui_backHomeButton;
}

