// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Error_Screen_screen_init(void)
{
    ui_Error_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Error_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Error_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Error_Screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainBlock1 = lv_obj_create(ui_Error_Screen);
    lv_obj_set_width(ui_MainBlock1, lv_pct(100));
    lv_obj_set_height(ui_MainBlock1, lv_pct(100));
    // lv_obj_set_x(ui_MainBlock1, -2);
    // lv_obj_set_y(ui_MainBlock1, -4);
    lv_obj_set_align(ui_MainBlock1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainBlock1, LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_MainBlock1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_MainBlock1, LV_DIR_VER);
    lv_obj_set_style_bg_image_src(ui_MainBlock1, &ui_img_1608614634, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_MainBlock1, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_MainBlock1, lv_color_hex(0x141415), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_MainBlock1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_MainBlock1, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainBlock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainBlock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainBlock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainBlock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainBlock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MainBlock1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image11 = lv_image_create(ui_Error_Screen);
    lv_image_set_src(ui_Image11, &ui_img_icons_fail_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Image11, -61);
    lv_obj_set_x(ui_Image11, lv_pct(0));
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firstErrorLabel = lv_label_create(ui_Error_Screen);
    lv_obj_set_width(ui_firstErrorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firstErrorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firstErrorLabel, -1);
    lv_obj_set_y(ui_firstErrorLabel, 55);
    lv_obj_set_align(ui_firstErrorLabel, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_firstErrorLabel, "RECHARGE SUCCESSFUL !!");
    lv_obj_set_style_text_color(ui_firstErrorLabel, lv_color_hex(0xECEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_firstErrorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_firstErrorLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondErrorLabel = lv_label_create(ui_Error_Screen);
    lv_obj_set_width(ui_secondErrorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondErrorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondErrorLabel, -9);
    lv_obj_set_y(ui_secondErrorLabel, 101);
    lv_obj_set_align(ui_secondErrorLabel, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_secondErrorLabel, "20 Unit Load Successfully");
    lv_obj_set_style_text_color(ui_secondErrorLabel, lv_color_hex(0xECEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondErrorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondErrorLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Error_Screen, ui_event_Error_Screen, LV_EVENT_ALL, NULL);

}
