// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_SplashScreen1_screen_init(void)
{
    ui_SplashScreen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SplashScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Block = lv_obj_create(ui_SplashScreen1);
    lv_obj_set_width(ui_Block, lv_pct(100));
    lv_obj_set_height(ui_Block, lv_pct(100));
    lv_obj_set_align(ui_Block, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Block, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Block, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Block, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Block, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Block, lv_color_hex(0x090808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Block, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Block, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Block, lv_color_hex(0x01010B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Block, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Block, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Block, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoBlock = lv_obj_create(ui_SplashScreen1);
    lv_obj_set_width(ui_logoBlock, LV_SIZE_CONTENT);   /// 252
    lv_obj_set_height(ui_logoBlock, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_logoBlock, -5);
    lv_obj_set_y(ui_logoBlock, lv_pct(-15));
    lv_obj_set_align(ui_logoBlock, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_logoBlock, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_logoBlock, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_logoBlock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_logoBlock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_logoBlock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_logoBlock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo1 = lv_image_create(ui_logoBlock);
    lv_image_set_src(ui_logo1, &ui_img_20240808_165355_png);
    lv_obj_set_width(ui_logo1, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_logo1, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_x(ui_logo1, -8);
    lv_obj_set_y(ui_logo1, -60);
    lv_obj_set_align(ui_logo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splashaction = lv_obj_create(ui_SplashScreen1);
    lv_obj_set_width(ui_splashaction, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_splashaction, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_splashaction, -8);
    lv_obj_set_y(ui_splashaction, 72);
    lv_obj_set_align(ui_splashaction, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_splashaction, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_splashaction, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_splashaction, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_splashaction, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splashaction, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_splashaction, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_splashaction);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 95);
    lv_obj_set_height(ui_Spinner1, 95);
    lv_obj_set_x(ui_Spinner1, -8);
    lv_obj_set_y(ui_Spinner1, 64);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x5D5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x11B7F2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LoadState = lv_label_create(ui_splashaction);
    lv_obj_set_width(ui_LoadState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadState, -6);
    lv_obj_set_y(ui_LoadState, 162);
    lv_obj_set_align(ui_LoadState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoadState, "Loading");
    lv_obj_set_style_text_color(ui_LoadState, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoadState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoadState, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SplashScreen1, ui_event_SplashScreen1, LV_EVENT_ALL, NULL);

}
