// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Success_Screen_screen_init(void)
{
    ui_Success_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Success_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Success_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Success_Screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainBlock2 = lv_obj_create(ui_Success_Screen);
    lv_obj_set_width(ui_MainBlock2, lv_pct(100));
    lv_obj_set_height(ui_MainBlock2, lv_pct(100));
    // lv_obj_set_x(ui_MainBlock2, -2);
    // lv_obj_set_y(ui_MainBlock2, -4);
    lv_obj_set_align(ui_MainBlock2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainBlock2, LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_MainBlock2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_MainBlock2, LV_DIR_VER);
    lv_obj_set_style_bg_image_src(ui_MainBlock2, &ui_img_1608614634, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_MainBlock2, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_MainBlock2, lv_color_hex(0x141415), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_MainBlock2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_MainBlock2, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainBlock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainBlock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainBlock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainBlock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainBlock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MainBlock2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_Success_Screen);
    lv_image_set_src(ui_Image12, &ui_img_icons_success_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Image12, -61);
    lv_obj_set_x(ui_Image12, lv_pct(0));
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firstSuccessLabel = lv_label_create(ui_Success_Screen);
    lv_obj_set_width(ui_firstSuccessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firstSuccessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firstSuccessLabel, -1);
    lv_obj_set_y(ui_firstSuccessLabel, 55);
    lv_obj_set_align(ui_firstSuccessLabel, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_firstSuccessLabel, "RECHARGE SUCCESSFUL !!");
    lv_obj_set_style_text_color(ui_firstSuccessLabel, lv_color_hex(0xECEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_firstSuccessLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_firstSuccessLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondSuccessLabel = lv_label_create(ui_Success_Screen);
    lv_obj_set_width(ui_secondSuccessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondSuccessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondSuccessLabel, -9);
    lv_obj_set_y(ui_secondSuccessLabel, 101);
    lv_obj_set_align(ui_secondSuccessLabel, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_secondSuccessLabel, "20 Unit Load Successfully");
    lv_obj_set_style_text_color(ui_secondSuccessLabel, lv_color_hex(0xECEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondSuccessLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondSuccessLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Success_Screen, ui_event_Success_Screen, LV_EVENT_ALL, NULL);

}
