// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_SplashScreen2_screen_init(void)
{
    ui_SplashScreen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SplashScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SplashScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SplashScreen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SplashScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SplashScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Block1 = lv_obj_create(ui_SplashScreen2);
    lv_obj_set_width(ui_Block1, lv_pct(100));
    lv_obj_set_height(ui_Block1, lv_pct(100));
    lv_obj_set_align(ui_Block1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Block1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Block1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Block1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Block1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Block1, lv_color_hex(0x090808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Block1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Block1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoBlock2 = lv_obj_create(ui_SplashScreen2);
    lv_obj_set_width(ui_logoBlock2, LV_SIZE_CONTENT);   /// 252
    lv_obj_set_height(ui_logoBlock2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_logoBlock2, 0);
    lv_obj_set_y(ui_logoBlock2, lv_pct(-12));
    lv_obj_set_align(ui_logoBlock2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_logoBlock2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_logoBlock2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_logoBlock2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_logoBlock2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_logoBlock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_logoBlock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_logoBlock2);
    lv_image_set_src(ui_Image2, &ui_img_20240808_153214_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -3);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splashaction2 = lv_obj_create(ui_SplashScreen2);
    lv_obj_set_width(ui_splashaction2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_splashaction2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_splashaction2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_splashaction2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_splashaction2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_splashaction2,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_splashaction2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splashaction2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_splashaction2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadLebel = lv_label_create(ui_splashaction2);
    lv_obj_set_width(ui_LoadLebel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadLebel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadLebel, -6);
    lv_obj_set_y(ui_LoadLebel, 157);
    lv_obj_set_align(ui_LoadLebel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoadLebel, "Reliable Energy, Anywhere, Anytime.");
    lv_obj_set_style_text_color(ui_LoadLebel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoadLebel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoadLebel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SplashScreen2, ui_event_SplashScreen2, LV_EVENT_ALL, NULL);

}
