// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Wifi_Setup_screen_init(void)
{
    ui_Wifi_Setup = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Wifi_Setup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Wifi_Setup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifi_Setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainBlock3 = lv_obj_create(ui_Wifi_Setup);
    lv_obj_set_width(ui_MainBlock3, lv_pct(100));
    lv_obj_set_height(ui_MainBlock3, lv_pct(100));
    // lv_obj_set_x(ui_MainBlock3, -2);
    // lv_obj_set_y(ui_MainBlock3, -4);
    lv_obj_set_align(ui_MainBlock3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainBlock3, LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_MainBlock3, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_MainBlock3, LV_DIR_VER);
    lv_obj_set_style_bg_image_src(ui_MainBlock3, &ui_img_1608614634, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_MainBlock3, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_MainBlock3, lv_color_hex(0x141415), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_MainBlock3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_MainBlock3, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainBlock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainBlock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainBlock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainBlock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainBlock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MainBlock3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_WifiList = lv_dropdown_create(ui_Wifi_Setup);
    lv_dropdown_set_text(ui_WifiList, "WIFI List");
    lv_obj_set_width(ui_WifiList, 163);
    lv_obj_set_height(ui_WifiList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiList, 73);
    lv_obj_set_y(ui_WifiList, -154);
    lv_obj_set_align(ui_WifiList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiList, LV_OBJ_FLAG_HIDDEN|LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_FLEX_IN_NEW_TRACK |
                    LV_OBJ_FLAG_SCROLL_ON_FOCUS);   /// Flags
    lv_obj_set_style_text_color(ui_WifiList, lv_color_hex(0xF7F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiList, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_WifiList, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiList, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WifiList, lv_color_hex(0x3D3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_WifiList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_WifiList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WifiList, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiList, lv_color_hex(0x28803F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WifiList, lv_color_hex(0x28803F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WifiList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WifiList, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WifiList, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_WifiList, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiList, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_WifiList), lv_color_hex(0xF9F4F4),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_WifiList), 200,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_WifiList), lv_color_hex(0x1D1E23),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_WifiList), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_WifiList), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_WifiList), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_WifiList), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiScan = lv_button_create(ui_Wifi_Setup);
    lv_obj_set_width(ui_wifiScan, 120);
    lv_obj_set_height(ui_wifiScan, 41);
    lv_obj_set_x(ui_wifiScan, -102);
    lv_obj_set_y(ui_wifiScan, -155);
    lv_obj_set_align(ui_wifiScan, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifiScan, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiScan, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiScan, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_radius(ui_wifiScan, 510, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiScan, lv_color_hex(0x111010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifiScan, lv_color_hex(0x333131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_wifiScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_wifiScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_wifiScan, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiScan, lv_color_hex(0x28803F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiScan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_wifiScan, lv_color_hex(0x28803F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_wifiScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifiScan, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifiScan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_text3 = lv_label_create(ui_wifiScan);
    lv_obj_set_width(ui_text3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_text3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_text3, -1);
    lv_obj_set_y(ui_text3, 3);
    lv_obj_set_align(ui_text3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_text3, "Scan");

    ui_keyboard = lv_keyboard_create(ui_Wifi_Setup);
    lv_obj_set_width(ui_keyboard, lv_pct(100));
    lv_obj_set_height(ui_keyboard, lv_pct(42));
    lv_obj_set_x(ui_keyboard, 3);
    lv_obj_set_y(ui_keyboard, 126);
    lv_obj_set_align(ui_keyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_radius(ui_keyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiLoading = lv_spinner_create(ui_Wifi_Setup);
    //lv_spinner_set_anim_params(ui_wifiLoading, 1000, 90);
    lv_obj_set_width(ui_wifiLoading, 80);
    lv_obj_set_height(ui_wifiLoading, 80);
    lv_obj_set_x(ui_wifiLoading, -4);
    lv_obj_set_y(ui_wifiLoading, -19);
    lv_obj_set_align(ui_wifiLoading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiLoading, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_wifiLoading, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_wifiLoading, lv_color_hex(0x2C2C2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_wifiLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_wifiLoading, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_wifiLoading, lv_color_hex(0x5F5F60), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_wifiLoading, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_wifiLoading, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PassWordText = lv_textarea_create(ui_Wifi_Setup);
    lv_obj_set_width(ui_PassWordText, 234);
    lv_obj_set_height(ui_PassWordText, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_PassWordText, -6);
    lv_obj_set_y(ui_PassWordText, -92);
    lv_obj_set_align(ui_PassWordText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PassWordText, "Enter Wifi Password");
    lv_textarea_set_one_line(ui_PassWordText, true);
    lv_textarea_set_password_mode(ui_PassWordText, true);
    lv_obj_add_state(ui_PassWordText, LV_STATE_EDITED);       /// States
    lv_obj_add_flag(ui_PassWordText, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags



    ui_backHomeButton = lv_imagebutton_create(ui_Wifi_Setup);
    lv_imagebutton_set_src(ui_backHomeButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_242677916, NULL);
    lv_imagebutton_set_src(ui_backHomeButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_242677916, NULL);
    lv_obj_set_height(ui_backHomeButton, lv_pct(6));
    lv_obj_set_width(ui_backHomeButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_backHomeButton, -206);
    lv_obj_set_y(ui_backHomeButton, -217);
    lv_obj_set_align(ui_backHomeButton, LV_ALIGN_CENTER);
    lv_obj_set_style_image_recolor(ui_backHomeButton, lv_color_hex(0x29CC0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_backHomeButton, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WifiList, ui_event_WifiList, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiScan, ui_event_wifiScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_keyboard, ui_event_keyboard, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_keyboard, ui_PassWordText);
    lv_obj_add_event_cb(ui_PassWordText, ui_event_PassWordText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backHomeButton, ui_event_backHomeButton, LV_EVENT_ALL, NULL);

}
