// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void logoFade_Animation(lv_obj_t * TargetObject, int delay);
void logoEventFade_Animation(lv_obj_t * TargetObject, int delay);
void slideup_Animation(lv_obj_t * TargetObject, int delay);
void scale_Animation(lv_obj_t * TargetObject, int delay);
void slidedown_Animation(lv_obj_t * TargetObject, int delay);
void gridstroke1_Animation(lv_obj_t * TargetObject, int delay);
void gridstroke2_Animation(lv_obj_t * TargetObject, int delay);
void solarstroke1_Animation(lv_obj_t * TargetObject, int delay);
void solarstroke2_Animation(lv_obj_t * TargetObject, int delay);
void inverterstroke1_Animation(lv_obj_t * TargetObject, int delay);
void inverterstroke2_Animation(lv_obj_t * TargetObject, int delay);
void btn_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_SplashScreen1
void ui_SplashScreen1_screen_init(void);
void ui_event_SplashScreen1(lv_event_t * e);
extern lv_obj_t * ui_SplashScreen1;
extern lv_obj_t * ui_Block;
extern lv_obj_t * ui_logoBlock;
extern lv_obj_t * ui_logo1;
extern lv_obj_t * ui_splashaction;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_LoadState;
// CUSTOM VARIABLES

// SCREEN: ui_SplashScreen2
void ui_SplashScreen2_screen_init(void);
void ui_event_SplashScreen2(lv_event_t * e);
extern lv_obj_t * ui_SplashScreen2;
extern lv_obj_t * ui_Block1;
extern lv_obj_t * ui_logoBlock2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_splashaction2;
extern lv_obj_t * ui_LoadLebel;
// CUSTOM VARIABLES

// SCREEN: ui_MAIN
void ui_MAIN_screen_init(void);
void ui_event_MAIN(lv_event_t * e);
extern lv_obj_t * ui_MAIN;
extern lv_obj_t * ui_MainBlock;
extern lv_obj_t * ui_bottomBar;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_bluetoothicon;
extern lv_obj_t * ui_wifiIcon;
extern lv_obj_t * ui_lockIcon;
extern lv_obj_t * ui_upsIcon;
extern lv_obj_t * ui_liteIcon;
extern lv_obj_t * ui_networkIcon;
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_HomeContibnner;
extern lv_obj_t * ui_sun;
extern lv_obj_t * ui_solarPanel;
extern lv_obj_t * ui_grid;
extern lv_obj_t * ui_pbx;
extern lv_obj_t * ui_load;
extern lv_obj_t * ui_batteryPack;
extern lv_obj_t * ui_batteryGuage;
extern lv_obj_t * ui_batteryContainner;
extern lv_obj_t * ui_chargingFlag;
extern lv_obj_t * ui_batteryHead;
extern lv_obj_t * ui_gridActive;
extern lv_obj_t * ui_gridstroke2;
extern lv_obj_t * ui_gridstroke1;
extern lv_obj_t * ui_gridstroke3;
extern lv_obj_t * ui_solarActive;
extern lv_obj_t * ui_solarstroke1;
extern lv_obj_t * ui_solarstroke2;
extern lv_obj_t * ui_solarstroke3;
extern lv_obj_t * ui_inverterActive;
extern lv_obj_t * ui_inverterstroke2;
extern lv_obj_t * ui_inverterstroke1;
extern lv_obj_t * ui_SwitchContainer;
void ui_event_pwrBtn(lv_event_t * e);
extern lv_obj_t * ui_pwrBtn;
extern lv_obj_t * ui_tabindicator;
extern lv_obj_t * ui_BattLabel;
extern lv_obj_t * ui_BattPercent;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_SolarVoltLabel;
extern lv_obj_t * ui_SolarVolt;
extern lv_obj_t * ui_volt2;
extern lv_obj_t * ui_gridlabel;
extern lv_obj_t * ui_gridVolt;
extern lv_obj_t * ui_volt;
extern lv_obj_t * ui_SolarCurLabel;
extern lv_obj_t * ui_SolarCurrent;
extern lv_obj_t * ui_curr;
extern lv_obj_t * ui_LoadVoltLabel;
extern lv_obj_t * ui_LoadVolt;
extern lv_obj_t * ui_volt3;
extern lv_obj_t * ui_LoadPwerLabel;
extern lv_obj_t * ui_loadPwr;
extern lv_obj_t * ui_curr2;
extern lv_obj_t * ui_topBar;
extern lv_obj_t * ui_Balcontainner;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_BalUnit;
extern lv_obj_t * ui_Label6;
void ui_event_MONITOR(lv_event_t * e);
extern lv_obj_t * ui_MONITOR;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_monitorContainner;
extern lv_obj_t * ui_total_Usage_container;
extern lv_obj_t * ui_totalUsage;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_usageGraph;
extern lv_obj_t * ui_usageGraph_Xaxis;
extern lv_obj_t * ui_usageGraph_Yaxis1;
extern lv_obj_t * ui_usageGraph_Yaxis2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_battVolt;
extern lv_obj_t * ui_cell1;
extern lv_obj_t * ui_cell2;
extern lv_obj_t * ui_cell3;
extern lv_obj_t * ui_solarVolt;
extern lv_obj_t * ui_Vsys;
extern lv_obj_t * ui_isys;
extern lv_obj_t * ui_vsys2;
extern lv_obj_t * ui_chargeCurrent1;
extern lv_obj_t * ui_Bal_Unit_Containner;
extern lv_obj_t * ui_totalUsage1;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Bal_Unit_Containner1;
extern lv_obj_t * ui_totalUnit;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_SETTING;
extern lv_obj_t * ui_Setting_Containner;
void ui_event_About(lv_event_t * e);
extern lv_obj_t * ui_About;
extern lv_obj_t * ui_text2;
extern lv_obj_t * ui_wifiContainner;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
void ui_event_wifiSwitch(lv_event_t * e);
extern lv_obj_t * ui_wifiSwitch;
extern lv_obj_t * ui_upscontianer;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image3;
void ui_event_upsSwitch(lv_event_t * e);
extern lv_obj_t * ui_upsSwitch;
extern lv_obj_t * ui_BackLight;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_bleContainner1;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image13;
void ui_event_bluetoothSwitch1(lv_event_t * e);
extern lv_obj_t * ui_bluetoothSwitch1;
// CUSTOM VARIABLES

// SCREEN: ui_Success_Screen
void ui_Success_Screen_screen_init(void);
void ui_event_Success_Screen(lv_event_t * e);
extern lv_obj_t * ui_Success_Screen;
extern lv_obj_t * ui_MainBlock2;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_firstSuccessLabel;
extern lv_obj_t * ui_secondSuccessLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Error_Screen
void ui_Error_Screen_screen_init(void);
void ui_event_Error_Screen(lv_event_t * e);
extern lv_obj_t * ui_Error_Screen;
extern lv_obj_t * ui_MainBlock1;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_firstErrorLabel;
extern lv_obj_t * ui_secondErrorLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Wifi_Setup
void ui_Wifi_Setup_screen_init(void);
extern lv_obj_t * ui_Wifi_Setup;
extern lv_obj_t * ui_MainBlock3;
void ui_event_WifiList(lv_event_t * e);
extern lv_obj_t * ui_WifiList;
void ui_event_wifiScan(lv_event_t * e);
extern lv_obj_t * ui_wifiScan;
extern lv_obj_t * ui_text3;
void ui_event_keyboard(lv_event_t * e);
extern lv_obj_t * ui_keyboard;
extern lv_obj_t * ui_wifiLoading;
void ui_event_PassWordText(lv_event_t * e);
extern lv_obj_t * ui_PassWordText;
void ui_event_backHomeButton(lv_event_t * e);
extern lv_obj_t * ui_backHomeButton;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_20240808_165355_png);    // assets/20240808_165355.png
LV_IMG_DECLARE(ui_img_20240808_153214_png);    // assets/20240808_153214.png
LV_IMG_DECLARE(ui_img_1608614634);    // assets/settings_bg (1).png
LV_IMG_DECLARE(ui_img_settings_bg_png);    // assets/settings_bg.png
LV_IMG_DECLARE(ui_img_icons_bluetooth24_png);    // assets/icons/bluetooth24.png
LV_IMG_DECLARE(ui_img_icons_wifi24_png);    // assets/icons/wifi24.png
LV_IMG_DECLARE(ui_img_icons_lock_png);    // assets/icons/lock.png
LV_IMG_DECLARE(ui_img_icons_ups_png);    // assets/icons/ups.png
LV_IMG_DECLARE(ui_img_icons_4g_png);    // assets/icons/4g.png
LV_IMG_DECLARE(ui_img_icons_net1_png);    // assets/icons/net1.png
LV_IMG_DECLARE(ui_img_279950534);    // assets/sun-48190 (1).png
LV_IMG_DECLARE(ui_img_1429571099);    // assets/—Pngtree—solar panels for energy_14101763 (1).png
LV_IMG_DECLARE(
    ui_img_745627511);    // assets/electrical-grid-solar-power-electricity-photovoltaic-power-station-overhead-power-line-others-c0982c7c094eb6105c526bd5f6df02b4 (1).png
LV_IMG_DECLARE(ui_img_1225420195);    // assets/Screenshot_2025-02-16_170140-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_628040357);    // assets/bulb-off-icon-26008 (1).png
LV_IMG_DECLARE(ui_img_water_3_png);    // assets/water_3.png
LV_IMG_DECLARE(ui_img_battery_bg_png);    // assets/battery_bg.png
LV_IMG_DECLARE(ui_img_icn_charge_png);    // assets/icn_charge.png
LV_IMG_DECLARE(ui_img_btn_knob_png);    // assets/btn_knob.png
LV_IMG_DECLARE(ui_img_960726147);    // assets/power-button-icon-8344 (3).png
LV_IMG_DECLARE(ui_img_628039206);    // assets/bulb-off-icon-26008 (2).png
LV_IMG_DECLARE(ui_img_pin_line_png);    // assets/pin_line.png
LV_IMG_DECLARE(ui_img_naira_png);    // assets/naira.png
LV_IMG_DECLARE(
    ui_img_602704857);    // assets/pngtree-renewable-energy-with-green-energy-as-wind-turbines-and-solar-panels-png-image_11529972 (1).png
LV_IMG_DECLARE(ui_img_2027358424);    // assets/—Pngtree—sun flare colored light_5348085 (1).png
LV_IMG_DECLARE(ui_img_896946180);    // assets/icons/connected-plug-icon.png
LV_IMG_DECLARE(ui_img_1776405879);    // assets/9380445 (2).png
LV_IMG_DECLARE(ui_img_1958972174);    // assets/icons/energy-meter-icon.png
LV_IMG_DECLARE(ui_img_59504384);    // assets/icons/sun-color-icon.png
LV_IMG_DECLARE(ui_img_icons_success_png);    // assets/icons/success.png
LV_IMG_DECLARE(ui_img_icons_fail_png);    // assets/icons/fail.png
LV_IMG_DECLARE(ui_img_242677916);    // assets/icons/reply-arrow-icon.png
LV_IMG_DECLARE(ui_img_icons_bluetooth24_png);    // assets/icons/bluetooth24.png
LV_IMG_DECLARE(ui_img_896946180);    // assets/icons/connected-plug-icon.png
LV_IMG_DECLARE(ui_img_1958972174);    // assets/icons/energy-meter-icon.png
LV_IMG_DECLARE(ui_img_1786102466);    // assets/icons/kwh-icon.png
LV_IMG_DECLARE(ui_img_222824350);    // assets/icons/lightning-icon.png
LV_IMG_DECLARE(ui_img_icons_monitor_png);    // assets/icons/monitor.png
LV_IMG_DECLARE(ui_img_510141704);    // assets/icons/setting-icon.png
LV_IMG_DECLARE(ui_img_146667093);    // assets/icons/smart-home-icon.png
LV_IMG_DECLARE(ui_img_59504384);    // assets/icons/sun-color-icon.png
LV_IMG_DECLARE(ui_img_icons_wifi24_png);    // assets/icons/wifi24.png
LV_IMG_DECLARE(ui_img_icons_lock_png);    // assets/icons/lock.png
LV_IMG_DECLARE(ui_img_icons_net0_png);    // assets/icons/net0.png
LV_IMG_DECLARE(ui_img_icons_net2_png);    // assets/icons/net2.png
LV_IMG_DECLARE(ui_img_icons_net3_png);    // assets/icons/net3.png
LV_IMG_DECLARE(ui_img_icons_net1_png);    // assets/icons/net1.png
LV_IMG_DECLARE(ui_img_icons_4g_png);    // assets/icons/4g.png
LV_IMG_DECLARE(ui_img_icons_fail_png);    // assets/icons/fail.png
LV_IMG_DECLARE(ui_img_icons_success_png);    // assets/icons/success.png
LV_IMG_DECLARE(ui_img_242677916);    // assets/icons/reply-arrow-icon.png
LV_IMG_DECLARE(ui_img_icons_ups_png);    // assets/icons/ups.png
LV_IMG_DECLARE(ui_img_1786102466);    // assets/icons/kwh-icon.png
LV_IMG_DECLARE(ui_img_222824350);    // assets/icons/lightning-icon.png
LV_IMG_DECLARE(ui_img_icons_monitor_png);    // assets/icons/monitor.png
LV_IMG_DECLARE(ui_img_icons_net0_png);    // assets/icons/net0.png
LV_IMG_DECLARE(ui_img_icons_net2_png);    // assets/icons/net2.png
LV_IMG_DECLARE(ui_img_icons_net3_png);    // assets/icons/net3.png
LV_IMG_DECLARE(ui_img_510141704);    // assets/icons/setting-icon.png
LV_IMG_DECLARE(ui_img_146667093);    // assets/icons/smart-home-icon.png
LV_IMG_DECLARE(ui_img_12471400_png);    // assets/12471400.png
LV_IMG_DECLARE(
    ui_img_1355713233);    // assets/abstract-luxury-blur-dark-grey-black-gradient-used-as-background-studio-wall-display-your-products_1258-54562 (1).png
LV_IMG_DECLARE(ui_img_bg_png);    // assets/bg.png
LV_IMG_DECLARE(ui_img_bottomtab_png);    // assets/bottomtab.png
LV_IMG_DECLARE(ui_img_btn_1_act_png);    // assets/btn_1_act.png
LV_IMG_DECLARE(ui_img_btn_1_inact_png);    // assets/btn_1_inact.png
LV_IMG_DECLARE(ui_img_menu_on_png);    // assets/menu_on.png
LV_IMG_DECLARE(ui_img_pin_on_png);    // assets/pin_on.png

// FONTS
LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Bold);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
