// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void power_ON(lv_event_t * e);
void power_OFF(lv_event_t * e);
void wifiON(lv_event_t * e);
void wifiOFFF(lv_event_t * e);
void bleON(lv_event_t * e);
void bleOFF(lv_event_t * e);
void upsON(lv_event_t * e);
void upsOFF(lv_event_t * e);
void wifiSELECT(lv_event_t * e);
void wifiSCAN(lv_event_t * e);
void wifiPasswordDetails(lv_event_t * e);
void  ui_BackLight_event_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
